import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

const quickSand = Quicksand({
  variable: "--font-reenie-beanie",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Interactive Library App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quickSand.variable} ${quickSand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
